modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

# Brandon's Core - Required
[[dependencies.${mod_id}]]
modId="brandonscore"
type="required"
versionRange="[${brandons_core_version},)"
ordering="NONE"
side="CLIENT"

# CodeChicken Lib - Required
[[dependencies.${mod_id}]]
modId="codechickenlib"
type="required"
versionRange="[${code_chicken_version},)"
ordering="NONE"
side="CLIENT"

# Draconic Evolution - Required
[[dependencies.${mod_id}]]
modId="draconicevolution"
type="required"
versionRange="[${draconic_evolution_version},)"
ordering="NONE"
side="CLIENT"

# Embeddium - Optional - either sodium or embeddium
[[dependencies.${mod_id}]]
modId="embeddium"
type="optional"
versionRange="[${embeddium_build_version},)"
ordering="NONE"
side="CLIENT"

# ImmediatelyFast - Optional
[[dependencies.${mod_id}]]
modId="immediatelyfast"
type="optional"
versionRange="[${immediately_fast_version},)"
ordering="AFTER"
side="CLIENT"

# Iris - Optional
[[dependencies.${mod_id}]]
modId="iris"
type="optional"
versionRange="[${iris_version},)"
ordering="AFTER"
side="CLIENT"

# Sodium - Optional - either sodium or embeddium
[[dependencies.${mod_id}]]
modId="sodium"
type="optional"
versionRange="[${sodium_version},)"
ordering="NONE"
side="CLIENT"
